name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-2.10.0-0.3.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.10.0-0.3.pre
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /1922-SMS-Tool/
